// <auto-generated />
using DungeonMaster.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DungeonMaster.Data.Migrations
{
    [DbContext(typeof(DungeonMasterDevContext))]
    [Migration("20171229233907_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DungeonMaster.Data.Models.AbilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("AbilityType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Background", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BackgroundTypeId")
                        .HasColumnName("BackgroundType_Id");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("BackgroundTypeId");

                    b.ToTable("Background");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.BackgroundType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("BackgroundType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Age");

                    b.Property<int>("BackgroundId")
                        .HasColumnName("Background_Id");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<decimal?>("Copper")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<decimal?>("Electrum")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<decimal?>("Gold")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<int?>("Height");

                    b.Property<int>("Level");

                    b.Property<decimal?>("Platinum")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int>("RaceId")
                        .HasColumnName("Race_Id");

                    b.Property<decimal?>("Silver")
                        .HasColumnType("numeric(18, 0)");

                    b.Property<int?>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("RaceId");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.CharacterAbilityScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AbilityTypeId")
                        .HasColumnName("AbilityType_Id");

                    b.Property<int>("CharacterId")
                        .HasColumnName("Character_Id");

                    b.Property<int>("Score");

                    b.HasKey("Id");

                    b.ToTable("Character_AbilityScore");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.ClassType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ClassType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Dndclass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClassTypeId")
                        .HasColumnName("ClassType_Id");

                    b.Property<string>("Desription")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("ParentClassId")
                        .HasColumnName("ParentClass_Id");

                    b.Property<int?>("SubClassTypeId")
                        .HasColumnName("SubClassType_Id");

                    b.HasKey("Id");

                    b.HasIndex("ClassTypeId");

                    b.HasIndex("ParentClassId");

                    b.HasIndex("SubClassTypeId");

                    b.ToTable("DNDClass");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Dndskill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AbilityTypeId")
                        .HasColumnName("AbilityType_Id");

                    b.Property<int>("SkillTypeId")
                        .HasColumnName("SkillType_Id");

                    b.HasKey("Id");

                    b.HasIndex("AbilityTypeId");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("DNDSkill");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<int>("FeatureTypeId")
                        .HasColumnName("FeatureType_Id");

                    b.Property<string>("Summary")
                        .HasColumnType("ntext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("FeatureTypeId");

                    b.HasIndex("Id")
                        .HasName("IX_Feature");

                    b.ToTable("Feature");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.FeatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("FeatureType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Proficiency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SavingThrowTypeId")
                        .HasColumnName("SavingThrowType_Id");

                    b.Property<int>("SkillTypeId")
                        .HasColumnName("SkillType_Id");

                    b.HasKey("Id");

                    b.HasIndex("SavingThrowTypeId");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("Proficiency");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("BaseSpeed");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("ParentRaceId")
                        .HasColumnName("ParentRace_Id");

                    b.Property<int>("RaceTypeId")
                        .HasColumnName("RaceType_Id");

                    b.Property<int?>("SubRaceTypeId")
                        .HasColumnName("SubRaceType_Id");

                    b.HasKey("Id");

                    b.HasIndex("ParentRaceId");

                    b.HasIndex("RaceTypeId");

                    b.HasIndex("SubRaceTypeId");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.RaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("RaceType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.SkillType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("SkillType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.SubClassType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("SubClassType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.SubRaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("SubRaceType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Background", b =>
                {
                    b.HasOne("DungeonMaster.Data.Models.BackgroundType", "BackgroundType")
                        .WithMany("Background")
                        .HasForeignKey("BackgroundTypeId")
                        .HasConstraintName("FK_Background_BackgroundType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Character", b =>
                {
                    b.HasOne("DungeonMaster.Data.Models.Background", "Background")
                        .WithMany("Character")
                        .HasForeignKey("BackgroundId")
                        .HasConstraintName("FK_Character_Background");

                    b.HasOne("DungeonMaster.Data.Models.Race", "Race")
                        .WithMany("Character")
                        .HasForeignKey("RaceId")
                        .HasConstraintName("FK_Character_Race");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.CharacterAbilityScore", b =>
                {
                    b.HasOne("DungeonMaster.Data.Models.AbilityType", "IdNavigation")
                        .WithOne("CharacterAbilityScore")
                        .HasForeignKey("DungeonMaster.Data.Models.CharacterAbilityScore", "Id")
                        .HasConstraintName("FK_Character_AbilityScore_AbilityType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Dndclass", b =>
                {
                    b.HasOne("DungeonMaster.Data.Models.ClassType", "ClassType")
                        .WithMany("Dndclass")
                        .HasForeignKey("ClassTypeId")
                        .HasConstraintName("FK_DNDClass_ClassType");

                    b.HasOne("DungeonMaster.Data.Models.Dndclass", "ParentClass")
                        .WithMany("InverseParentClass")
                        .HasForeignKey("ParentClassId")
                        .HasConstraintName("FK_Class_ParentClass");

                    b.HasOne("DungeonMaster.Data.Models.SubClassType", "SubClassType")
                        .WithMany("Dndclass")
                        .HasForeignKey("SubClassTypeId")
                        .HasConstraintName("FK_DNDClass_SubClassType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Dndskill", b =>
                {
                    b.HasOne("DungeonMaster.Data.Models.AbilityType", "AbilityType")
                        .WithMany("Dndskill")
                        .HasForeignKey("AbilityTypeId")
                        .HasConstraintName("FK_DNDSkill_AbilityType");

                    b.HasOne("DungeonMaster.Data.Models.SkillType", "SkillType")
                        .WithMany("Dndskill")
                        .HasForeignKey("SkillTypeId")
                        .HasConstraintName("FK_DNDSkill_SkillType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Feature", b =>
                {
                    b.HasOne("DungeonMaster.Data.Models.FeatureType", "FeatureType")
                        .WithMany("Feature")
                        .HasForeignKey("FeatureTypeId")
                        .HasConstraintName("FK_Feature_FeatureType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Proficiency", b =>
                {
                    b.HasOne("DungeonMaster.Data.Models.AbilityType", "SavingThrowType")
                        .WithMany("Proficiency")
                        .HasForeignKey("SavingThrowTypeId")
                        .HasConstraintName("FK_Proficiency_SavingThrow");

                    b.HasOne("DungeonMaster.Data.Models.SkillType", "SkillType")
                        .WithMany("Proficiency")
                        .HasForeignKey("SkillTypeId")
                        .HasConstraintName("FK_Proficiency_SkillType");
                });

            modelBuilder.Entity("DungeonMaster.Data.Models.Race", b =>
                {
                    b.HasOne("DungeonMaster.Data.Models.Race", "ParentRace")
                        .WithMany("InverseParentRace")
                        .HasForeignKey("ParentRaceId")
                        .HasConstraintName("FK_Race_ParentRace");

                    b.HasOne("DungeonMaster.Data.Models.RaceType", "RaceType")
                        .WithMany("Race")
                        .HasForeignKey("RaceTypeId")
                        .HasConstraintName("FK_Race_RaceType");

                    b.HasOne("DungeonMaster.Data.Models.SubRaceType", "SubRaceType")
                        .WithMany("Race")
                        .HasForeignKey("SubRaceTypeId")
                        .HasConstraintName("FK_Race_SubRaceType");
                });
#pragma warning restore 612, 618
        }
    }
}
